### ISSUE TITLE
Safeguards for the fakeSlots property

### ISSUE THREAD

**Issue by patgoat** [Cr1mDev/SlotsPlus#2]
Currently it is possible to set the fakeSlots property to a number greater or equal to the  maximum player count, therefore making it impossible to join.

The plugin should contain checks for if the fakeSlots property is greater the maximum player count or equal to.

The plugin should also add the fakeplayers instead of setting the player count to it, as you can have it set to 1, but there could be 100 players, the plugin will only show 1 player

**Comment by AreroLR** [comment]
Added the check in [v1.5](https://github.com/Cr1mDev/SlotsPlus/releases/tag/v1.5).
